export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  REGISTERBOAT: "/register-boat",
  ADD_BOAT: "/boat/add",
  EDIT_BOAT: "/boat/edit/:id",
  INFO_BOAT: "/boat/info/:id",
  REGISTERSUBSCRIPTION: "/register-subscription",
  REGISTERPAYMENT: "/register-payment",
  REGISTERCARD: "/register-card",
  PROFILE: "/profile",
  PROFILE_EDIT: "/profile/edit",
  INFO: "/info",
  NOT_FOUND: "*",
};
